[build]
command = "pip install -r requirements.txt"
functions = "netlify/functions"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/.netlify/functions/bot"
status = 200